export {
  addToWatchlist,
  followAuthor,
  getAuthorById,
  getAuthors,
  getFollowedAuthorIds,
  getFollowedAuthors,
  getFollowerCount,
  getMarkets,
  getSnapshotsByTradeId,
  getTradeById,
  getTrades,
  getTradesForFollowedAuthors,
  getUserById,
  getWatchedTradeIds,
  getWatchlist,
  getWatchlistTrades,
  recomputeAuthorStats,
  removeFromWatchlist,
  saveSnapshot,
  unfollowAuthor,
  upsertAuthor,
  upsertMarket,
  upsertTrade,
  upsertUser,
} from "./db-sqlite";
